### PR TITLE
fix copyright; reorder file (Brew metadata...

### PR DESCRIPTION
**Pull request by nickboldt**
fix copyright; reorder file (Brew metadata at end); update to split operator and operator-metadata into two containers; update base images

Change-Id: I1e6c4152245fe645a7f40b8726351064a5c42ec1
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by tolusha** [comment]
How it will effect the release process?

**Comment by nickboldt** [comment]
Che release process: unchanged (this file is not used).

CRW release process: makes it easier to sync with upstream.

**Comment by tolusha** [comment]
@nickboldt 
Pls, have a look
```
Run docker build .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/che-operator/che-operator/Dockerfile: no such file or directory
##[error]Process completed with exit code 1.
```

**Comment by nickboldt** [comment]
Yes, as I later realized, the Dockerfile *IS* used by upstream. So... I'll rework this PR so it removes the Brew metadata and reorders stuff. We can then use the same Dockerfile for both upstream Che and downstream (once transformed) CRW brew builds.

**Comment by nickboldt** [comment]
OK, now the PR is much cleaner: 
* update copyright
* update base image tags
* remove brew metadata (it's added downstream)

**Pull request merged**
