### PR TITLE
Update plugin brokers to v3.4.0

### PR DESCRIPTION
**Pull request by amisevsk**

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Comment by tolusha** [comment]
@amisevsk 
pls run `olm/update-nightly-olm-files.sh`
and commit generated files as well.

**Review by tolusha — APPROVED** [review]
Pls merge. 
Don't take into account  failed update tests.

**Comment by tolusha** [comment]
@amisevsk 
Why do we have v3.3.0. in https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties ?
```
che.workspace.plugin_broker.metadata.image=quay.io/eclipse/che-plugin-metadata-broker:v3.3.0
che.workspace.plugin_broker.artifacts.image=quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0
```

**Comment by tolusha** [comment]
I am going to revert these changes in this PR https://github.com/eclipse/che-operator/pull/442

**Comment by amisevsk** [comment]
@tolusha I'm not sure what you mean here. https://github.com/eclipse/che/pull/17785 updates che.properties, but note that those properties are *completely* meaningless since the operator will always override them. I'm pretty sure reverting the `3.4.0` change will just break PR check again on my PR.

**Pull request merged**
