### PR TITLE
Fix broken Openshift e2e test.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
In the pr was recovered right defaut oauth value: https://github.com/eclipse/che-operator/commit/0a54abd1e19e93b6dbe69d3b9b0c0cc84258512a#diff-accaba0f96f2bc96246cfa30da71ff64R30

But test was not ready for this value.

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Review by flacatus — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
> ci/prow/v4-che-operator-update

Strange locally this test works with crc 4.5...

**Comment by AndrienkoAleksandr** [comment]
Issue with update test is reproducible for another pr's. It's not regression of the current pr, so I merge it.

**Pull request merged**
