### PR TITLE
Adding 'eclipse-che' as the suggested namespace

### PR DESCRIPTION
**Pull request by ibuziuk**
Adding 'eclipse-che' as the suggested namespace.

- UX when "eclipse-che" namespace does not exist on the cluster: 

image

- UX when "eclipse-che" namespace exists on the cluster: 

image

This is the initial step for https://github.com/eclipse/che/issues/17187

### CODE REVIEW

**Comment by ibuziuk** [comment]
@davidfestal @tolusha any pointers on how the OperatorHub installation can be tested?  During the olm installation the namespace is already specified - https://github.com/eclipse/che-operator/blob/master/README.md#how-to-test-operator-via-olm

Basically, I want to test the WebConsole UX with the 'operatorframework.io/suggested-namespace: eclipse-che' annotation -  https://docs.openshift.com/container-platform/4.4/operators/operator_sdk/osdk-generating-csvs.html#osdk-suggested-namespace_osdk-generating-csvs

**Comment by tolusha** [comment]
@ibuziuk 
pls don't merge until https://github.com/eclipse/che-operator/pull/274 (it is going to be merged today)

**Comment by ibuziuk** [comment]
@tolusha I'm not going to merge it without review ;) Any pointers how to test the nighly olm from scratch with the manual approval step without specifying namespace etc.

```chectl server:start --installer=olm --multiuser --platform=openshift -n che-namespace --catalog-source-yaml /home/user/path/to/custom-catalog-source.yaml --olm-channel=nightly --package-manifest-name=eclipse-che-preview-openshift```

the command from the docs already deploys everything in one go, and as part of this PR I need to test the WebConsole UX.

**Comment by tolusha** [comment]
@ibuziuk 
no, I don't know how.
maybe @AndrienkoAleksandr @davidfestal

**Comment by AndrienkoAleksandr** [comment]
We have a doc https://github.com/eclipse/che-operator/blob/master/README.md#how-to-test-operator-via-olm

**Comment by AndrienkoAleksandr** [comment]
Yes, this docs https://github.com/eclipse/che-operator/blob/master/README.md#how-to-test-operator-via-olm should help.

**Comment by AndrienkoAleksandr** [comment]
@ibuziuk I applied little update for this doc to prevent some update issue: 
https://github.com/eclipse/che-operator/pull/329

**Comment by davidfestal** [comment]
> Yes, this docs https://github.com/eclipse/che-operator/blob/master/README.md#how-to-test-operator-via-olm should help.

Especially the points 4 and 5:

> 4. Build catalog source image.
> Go to `olm/eclipse-che-preview-openshift` folder and build the image: `docker build -t user/custom-catalog-source:latest .`
> Push it into your docker registry.
> 
> 5. Create custom catalog source yaml:
> ```yaml
> apiVersion:  operators.coreos.com/v1alpha1
> kind:         CatalogSource
> metadata:
>   name:         eclipse-che-preview-openshift
>   namespace:    che-namespace
> spec:
>   image:        docker.io/user/custom-catalog-source:latest
>   sourceType:  grpc
> ```
> Replace value of `image` field with your catalog source image.

But you should add probably add this catalog source **in the `openshift-marketplace` namespace** (the global operators namespace), to be compatible with the `AllNamespace` install mode.

Then you can create an OpenShift 4.5 cluster (by cluster-bot ?) and apply this catalog source.
As soon as the catalog source it is applied, and reconciled, you should see the operator (marked as "custom") proposed in the list of operators in OperatorHub.

**Comment by AndrienkoAleksandr** [comment]
> add probably add this catalog source in the openshift-marketplace namespace (the global operators namespace), to be compatible with the AllNamespace install mode

Good remark for this case.

**Comment by ibuziuk** [comment]
@tolusha @davidfestal @AndrienkoAleksandr thanks for the help with instructions. PR is ready for review

**Comment by nickboldt** [comment]
So if we want to override the default, we'd set something different in the CSV?

```
- operatorframework.io/suggested-namespace: eclipse-che
+ operatorframework.io/suggested-namespace: codeready-workspaces
```

**Comment by ibuziuk** [comment]
@nickboldt more likely it will be `operatorframework.io/suggested-namespace: openshift-che` or `operatorframework.io/suggested-namespace: redhat-che`

**Comment by nickboldt** [comment]
OK, so that's a change from CRW 1.x and 2.0-2.2 behaviour then, where the default namespace (eg., if you don't tell `crwctl` to use a custom value) == `workspaces`

```
  -n, --chenamespace=chenamespace
      [default: workspaces] Kubernetes namespace where CodeReady Workspaces server is supposed to be deployed
```

I would expect that we would NOT want to see "che" in the product's namespace... it's already in way too many hardcoded places today, like the env vars and che.properties. Must we add another one?

**Comment by nickboldt** [comment]
Right now in CRW 2.3 we have suggested namespace = `workspaces`

```
** [1] ./build/scripts/sync-che-olm-to-crw-olm.sh ** 
126-		\
127-		` # TODO is this the correct value to set here?` \
128:		-e 's|operatorframework.io/suggested-namespace: .+|operatorframework.io/suggested-namespace: workspaces|' \
129-		-i "${CSVFILE}"
130-	# insert missing cheFlavor annotation

** [3] ./manifests/codeready-workspaces.csv.yaml ** 
55-      developer workspaces in OpenShift.
56-    operatorframework.io/cluster-monitoring: "true"
57:    operatorframework.io/suggested-namespace: workspaces
58-    repository: https://github.com/redhat-developer/codeready-workspaces-operator/
59-    support: Red Hat

```

**Pull request merged**
