### PR TITLE
CRW-979 use strings.TrimPrefix instead of...

### PR DESCRIPTION
**Pull request by nickboldt**
CRW-979 use strings.TrimPrefix instead of strings.TrimLeft

Change-Id: I7969e88c84ab211738fe071313ccc0fae4bac25c
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
I don't see what needs to be updated. The test passed. :shrug:

**Comment by gorkem** [comment]
@AndrienkoAleksandr Curious, How did you approve this PR? Did you test it for instance against the url that is originally reported broken "http://proxy.customer.com" ?

**Comment by davidfestal** [comment]
> I don't see what needs to be updated. The test passed. 🤷

I somehow agree that we should add a test with the proxy URL that initially produced the failure.
So that if someone changes the code back to `strings.TrimLeft`, the error will this time be caught by unit tests.

**Comment by mmorhun** [comment]
I've created a separate PR which must fix the issue: https://github.com/eclipse/che-operator/pull/315

**Pull request closed without merging**
