### PR TITLE
Add RELEASE.md

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### What does this PR do
- Adds `make-release.sh` to automate most of the steps.
- Adds `RELEASE.md`

`make-release.sh` hasn't been tested yet since it requires a real release to perform.

### CODE REVIEW

**Comment by tolusha** [comment]
@nickboldt 
It is for upcoming release.

**Comment by nickboldt** [comment]
I could merge this now and if it needs tweaking after 7.8.0, we can add a new PR; or we can wait until 7.8.0 release confirms this PR works as expected.

Preference?

**Comment by tolusha** [comment]
I prefer to merge it and tweak during next releases....

**Comment by nickboldt** [comment]
OK, merged.

**Pull request merged**
