### PR TITLE
Copy 7.17.2 csv to master

### PR DESCRIPTION
**Pull request by mkuznyetsov**

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
Job `ci/prow/v5-che-operator-olm-latest-changes-tests` is not working because seems there is a problem in Eclipse Che Nightly server... That is not related with this PR:
LOGS from che server nightly:

2020-08-20 07:49:05,279[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 691]    - Workspace 'admin/e2e-tests' with id 'workspaceszr0jllw76xs1n0t' created by user 'admin'
2020-08-20 07:49:08,636[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'admin/e2e-tests' with id 'workspaceszr0jllw76xs1n0t' by user 'admin'
2020-08-20 07:52:34,668[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 247]  - Failed to start Kubernetes runtime of workspace workspaceszr0jllw76xs1n0t. Cause: Plugins installation process timed out
2020-08-20 07:52:34,735[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'admin:e2e-tests' with id 'workspaceszr0jllw76xs1n0t' start failed

**Comment by tolusha** [comment]
@flacatus 
It is related to pluginbrocker changes.
https://github.com/eclipse/che/issues/17670
https://github.com/eclipse/che/pull/17671

**Comment by flacatus** [comment]
[test]

**Comment by mkuznyetsov** [comment]
[test]

**Comment by mkuznyetsov** [comment]
minishift update was tested with chectl

**Pull request merged**
