### PR TITLE
Delete unused files. Earlier we used these files for removed olm/update-nightly-olm-files.sh

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### Referenced issue:
none. Code cleanup.

Delete unused files. Earlier we used these files for removed olm/update-nightly-olm-files.sh

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
Thanks @tolusha CI is green

**Pull request merged**
