### PR TITLE
Set tlsSupport to true by default

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

Sets `tlsSupport` field of Che CR to `true`:
```yaml
spec:
  server:
    tlsSupport: true
```

To set TLS support back to `false` (which is not recommended),  one need to run `chectl` with `--che-operator-cr-patch-yaml=patch.yaml` flag (create the patch file from the snippet above, but change the value to `false`).

### CODE REVIEW

**Comment by davidfestal** [comment]
You should also update the OLM nightlies (running the script) and then manually change the ALM example annotation in the new nightly CSVs.

**Comment by tolusha** [comment]
> Please add the same changes in OLM files

What does it mean?

**Comment by AndrienkoAleksandr** [comment]
I think @mmorhun should generate new nightly CVS

**Comment by davidfestal** [comment]
> > Please add the same changes in OLM files
> 
> What does it mean?

Sorry I was referring to my [previous comment](https://github.com/eclipse/che-operator/pull/186#issuecomment-595769277):

> You should also update the OLM nightlies (running the script) and then manually change the ALM example annotation in the new nightly CSVs.

**Comment by erlansan** [comment]
> Signed-off-by: Mykola Morhun [mmorhun@redhat.com](mailto:mmorhun@redhat.com)
> 
> Sets `tlsSupport` field of Che CR to `true`:
> 
> ```yaml
> spec:
>   server:
>     tlsSupport: true
> ```
> 
> To set TLS support back to `false` (which is not recommended), one need to run `chectl` with `--che-operator-cr-patch-yaml=patch.yaml` flag (create the patch file from the snippet above, but change the value to `false`).

Hello, thank you for the possible solution! Would it be possible to describe in more detail, where this option is located and how to change it? I'm simply running the commands and getting all of the images from the internet. After reading your solution i'm still yet to understand how to do it. Hope it wont be much trouble, thanks in advance!

**Comment by AndrienkoAleksandr** [comment]
For latest Che `tlsSupport: true` is always true and field is deprecated. See more https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L445

**Comment by erlansan** [comment]
> @erlansan For latest Che `tlsSupport: true` is always true and field is deprecated. See more https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L445

I see that. I believe i need to do one of 2 things. Either turn off tsl, or create my own sertificates. I'm currently running into the issue of not being able to start eclipse che on my minishift cluster because i don't have TSL sertificates configured, and minishifts sertificates are not valid(i belive some of developers mentioned that minishift is deprecated at the time)
So therefore i'm not able to start Eclipse Che pod and getting a timeout error. 
I tried figuring out how to create selft signed certificates in Windows, but so far with no success because i'm lacking the expertise to configure it properly(since all of existing commands are tailored for linux based systems)
Therefore i'm asking for some kind of direction, how can i bypass that issue of not being able to run Eclipse Che. If i could turn off tsl support, than i believe i could be able to start Eclipse Che on minishift withoud the pod timing out. I would really appreciate if you could help me out with that.

**Comment by tolusha** [comment]
@eriawan 
Pls follow this guide to install Eclipse Che on Minishift with tls enabled

https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#deploying-che-with-self-signed-tls-certificates-on-openshift-3_installing-che-in-tls-mode-with-self-signed-certificates

**Comment by AndrienkoAleksandr** [comment]
I guess we need write some docs about generation certificates on the Windows...

**Comment by erlansan** [comment]
@tolusha  and @AndrienkoAleksandr  thank you for quick really! I really appreciate that
@tolusha i tried using the https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#generating-self-signed-tls-certificates_installing-che-in-tls-mode-with-self-signed-certificates docu on windows, finding the equivalents of the commands for windows, but no luck, can't get it to work for me. I'm aware of that guide and therefore asked if there is some guidance for windows users, because i lack the knowledge of reqired commands on both OS(windows and linux).

**Comment by tolusha** [comment]
@erlansan 
I see. Despite the flag `tlsSupport` is deprecated we still have working api.
Try set it to false in your CR.

**Pull request merged**
