### PR TITLE
Minor: Fix little typo.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Comment by tolusha** [comment]
[test]

**Comment by flacatus** [comment]
@tolusha I think is better to merge this PR first: https://github.com/eclipse/che-operator/pull/165

**Comment by tolusha** [comment]
[test]

**Comment by tolusha** [comment]
@rhopp 
Could you have a look at build log?

https://ci.centos.org/job/devtools-che-operator-pr-check/12/console

**Comment by AndrienkoAleksandr** [comment]
I re-based branch to the master. I hope it will fix build.

**Pull request merged**
