### PR TITLE
CRW-316 we don't need to keep the CRW...

### PR DESCRIPTION
**Pull request by nickboldt**
CRW-316 we don't need to keep the CRW controller-manifests in this repo

Change-Id: Ibb7c5b1695e527e5851c3a00f27f0548f553fa73
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
In addition to this change the CRW operator sync job will now need to apply one extra sed patch:

```
sed -e "s@# *ADD controller-manifests /manifests@/ADD controller-manifests /manifests@g"
```

**Comment by nickboldt** [comment]
> So the corresponding yaml files will be stored in the downstream repo already now ?

They already are: http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces-operator/tree/controller-manifests?h=crw-1.2-rhel-8

**Comment by nickboldt** [comment]
Also cherrypicked to master: https://github.com/eclipse/che-operator/commit/80c96cc9be9fe6f2a0c24636c86dcf23b5d11aea

**Comment by davidfestal** [comment]
Thanks @nickboldt !

**Pull request merged**
