### PR TITLE
bump to latest...

### PR DESCRIPTION
**Pull request by nickboldt**
bump to latest registry.access.redhat.com/ubi8-minimal:8.1-398

Change-Id: I5a648aba1bca8c9dbacdff0bcf4722684d27a78a
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by davidfestal** [comment]
Approved, but doesn't it miss update to OLM files ? Is it expected to do this is a distinct PR ?

**Comment by nickboldt** [comment]
Which files do you mean? Aren't all files under `olm/eclipse-che-preview-*/` immutable once created, eg., 7.9.0 or 9.9.9-nightly-1582546871 ?

Is there some version of those files used as a template for future ones?

**Comment by flacatus** [comment]
[test]

**Comment by nickboldt** [comment]
updated to resolve conflict (newer 9.9.9.x files created after this PR was approved).

If you like a PR, and it's got approvals and passing tests, just feel free to merge it. no need to wait for the author. :D

**Pull request merged**
