### PR TITLE
Adding ARM support

### PR DESCRIPTION
**Pull request by ghatwala**
Adding ARM support .

Signed-off-by: Amit Ghatwal ghatwala@us.ibm.com

### CODE REVIEW

**Comment by sleshchenko** [comment]
@ghatwala The eclipsefdn/eca check failed. See https://accounts.eclipse.org/legal/eca/validation/38657
Probably `< >` for email are missing in your signing footer. See https://github.com/eclipse/che-operator/commits/master

**Comment by ghatwala** [comment]
@sleshchenko  - thanks for catching that ...looks like a stringent requirement from eclipsefd/eca . :)

**Comment by tolusha** [comment]
[test]

**Comment by tolusha** [comment]
@ghatwala 
Sorry for delay. 
Is it still relevant?

**Comment by ghatwala** [comment]
Would be good to have - @tolusha ...

**Pull request merged**
