### PR TITLE
Add note clarifying that the kubernetes image puller operator is comm…

### PR DESCRIPTION
**Pull request by tomgeorge**
…unity-supported

Signed-off-by: Tom George <tgeorge@redhat.com>

### What does this PR do?

As part of the discussions around how to best add the kubernetes image puller into the che-operator[1], this PR adds a note that the image puller is considered community supported.

[1] See:

eclipse/che#18569
eclipse/che#18133
#541

### Screenshot/screencast of this PR

imagepuller

### What issues does this PR fix or reference?

eclipse/che#18569
eclipse/che#18133
#541

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse/che-operator/blob/master/README.md#updating-custom-resource-definition-file)
- [x] [Nightly OLM bundle is up to date](https://github.com/eclipse/che-operator/blob/master/README.md#update-nightly-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Review by tolusha — APPROVED** [review]

**Review by nickboldt — APPROVED** [review]
since I wrote the suggested new 'please note' addendum and 'community supported' descriptor, implied +1. :D

**Comment by sympatheticmoose** [comment]
Just to check, this will be disabled by default as shown in the screenshot? The user will have to choose to enable it - correct?

**Comment by tomgeorge** [comment]
@sympatheticmoose that's correct

**Comment by tolusha** [comment]
I've updated nightly bundle. For some reasons check passed but files weren't up to date.

**Comment by tolusha** [comment]
Also I've removed empty line in a comment.

**Review by davidfestal — APPROVED** [review]

**Pull request merged**
