### PR TITLE
latest go in devtools/go-toolset-rhel7 is go...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

latest go in devtools/go-toolset-rhel7 is go 1.14, so use that in Che and CRW builds

Change-Id: Ib2ac4b85ebbf210e887012edb179a3146229df78
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
CRW-1442 - need to use latest golang to build CRW, and might as well use same upstream too :D

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
It is not enough to switch to golang 1.14
/cc @AndrienkoAleksandr 

@nickboldt 
Do we really need this for upstream ?

**Comment by nickboldt** [comment]
if not moving to go 1.14, I need:
* reason why not to move to latest in both up and downstream, or 
* mechanism to override latest base image (1.14-x) with latest **1.13** image instead (a sed hack likely in the operator jenkinsfile)

**Comment by nickboldt** [comment]
Counter offer - we can use golang 1.13 in downstream with this patch:

https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/commit/6395fc971bf01fe2a0b1cca66a63992484bd3ce6#ad7e5d54432b2dfb91b1cf6437313e830429b506_142_148

**Comment by tolusha** [comment]
I see. I am basically ok
But isn't not enough just to update Dockerfile
We have to update go.mod as well

**Comment by nickboldt** [comment]
image

**Comment by nickboldt** [comment]
Cherrypicked to 7.24.x branch for 7.24.1

**Pull request merged**
