### PR TITLE
Use architecture dependent images

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### Reference issue
https://issues.redhat.com/browse/CRW-1131

### What does this PR do
Using architecture dependent images.

### CODE REVIEW

**Comment by nickboldt** [comment]
Once this is merged for Che 7.18, the followup work for CRW 2.4 would be to:
* insert RELATED_IMAGE_keycloak_s390x = `SSO for Z image`
* insert RELATED_IMAGE_keycloak_ppc64le = `SSO for Power image`

into the csv for CRW 2.4.

Correct?

**Comment by tolusha** [comment]
@nickboldt 
Correct

**Pull request merged**
