### PR TITLE
CRW-445 remove tls and self-signed certs params from csv

### PR DESCRIPTION
**Pull request by nickboldt**
remove tls and self-signed certs params from cvs template

Change-Id: I7c90faaab8387fc89a459ed8673abe5be2365365
Signed-off-by: nickboldt <nboldt@redhat.com>

Fix for:

https://issues.redhat.com/browse/CRW-445

### CODE REVIEW

**Comment by flacatus** [comment]
@nickboldt There is a bug in CI with Minishift job. Please skip.

**Comment by nickboldt** [comment]
@flacatus does that mean you approve of this change?

**Comment by tolusha** [comment]
@nickboldt 
This is correct place.
Pls update kubernetes files as well.

**Comment by nickboldt** [comment]
Thanks! I've also cherrypicked this to 7.16.x branch so we can have it in CRW 2.3.

**Pull request merged**
