### PR TITLE
prepare operator namespace cluster-role

### PR DESCRIPTION
**Pull request by sparkoo**
Prepare `che-namespace-editor` ClusterRole and ClusterRoleBindings in operator deployment.

This is first step to grant `update` and `get` `namespaces` permissions to `che` ServiceAccount.

Issue: https://github.com/eclipse/che/issues/18272

### CODE REVIEW

**Comment by sparkoo** [comment]
@tolusha is it normal that minikube and minishift CI fails?

**Comment by tolusha** [comment]
1. Update the following files correspondingly.
  - https://github.com/sparkoo/che-operator/blob/gh18272-namespacePermissions/deploy/olm-catalog/eclipse-che-preview-openshift/build-roles.sh
  - https://github.com/sparkoo/che-operator/blob/gh18272-namespacePermissions/olm/eclipse-che-preview-openshift/build-roles.sh
  - https://github.com/sparkoo/che-operator/blob/gh18272-namespacePermissions/deploy/olm-catalog/eclipse-che-preview-openshift/build-roles.sh#L19
2. Run olm/update-nightly-bundle.sh to update nightly csv files with new roles
3. Commit new changes

**Comment by tolusha** [comment]
As far as I understand we need new cluster roles for both k8s and OpenShift, right?

**Comment by sparkoo** [comment]
> As far as I understand we need new cluster roles for both k8s and OpenShift, right?

That's right. It's used to label the workspace namespaces, no matter on what infra we are.

**Comment by sparkoo** [comment]
>     1. Update the following files correspondingly.
> 
> 
>     * `build-roles.sh` files
> 
>     * `csv-config.yaml` files
> 
> 
>     1. Run olm/update-nightly-bundle.sh to update nightly csv files with new roles
> 
>     2. Commit new changes

I have no idea what I've just done, but I've commited result of these steps :)

**Comment by tolusha** [comment]
I did some trick ;)

**Comment by AndrienkoAleksandr** [comment]
Changes with cluster role and bindings looks good.

**Review by tolusha — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by sparkoo** [comment]
I hope I've rebased it correctly.

@davidfestal can you please review?

**Comment by sparkoo** [comment]
I've move this PR to draft, because I've tried to actually assign the `che-namespace-editor` ClusterRole to `che` ServiceAccount, and che-operator does not have permissions to manage ClusterRoles. So we would need to update this as well. I'll update the PR.

**Comment by tolusha** [comment]
@sparkoo 
I am wondering how you figured that out. 
Maybe our tests doesn't cover something...

**Comment by sparkoo** [comment]
> @sparkoo
> I am wondering how you figured that out.
> Maybe our tests doesn't cover something...

@tolusha che-opearator is not creating any ClusterRoleBinding at the moment. As I was doing that, I hit the permissions wall. See this changes https://github.com/sparkoo/che-operator/pull/3/files

**Comment by sparkoo** [comment]
@tolusha @AndrienkoAleksandr I've updated the PR with new permissions for che-operator. Please re-review.

**Comment by tolusha** [comment]
k8s csv files aren't updated with the content below due to fact that build-roles.sh doesn't include `cluster-role.yaml` file as well as csv-config.yaml

```
- apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - list
      - create
      - watch
```

**Comment by sparkoo** [comment]
rebased

**Comment by tolusha** [comment]
@sparkoo 
I will handle that and provide a commit soon

**Comment by tolusha** [comment]
Blocked by https://github.com/eclipse/che/issues/18349

**Comment by tolusha** [comment]
Updated csv using old version of the operator-sdk.
Let's wait for green light.

**Review by tolusha — APPROVED** [review]

**Comment by sparkoo** [comment]
@tolusha do you want to wait for @davidfestal to review? Or are we ready to merge?

**Comment by tolusha** [comment]
@sparkoo you can merge.

**Pull request merged**
