### PR TITLE
Fix secret creation in the latest csv

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### Reference issue
https://github.com/eclipse/che/issues/16097

### CODE REVIEW

**Comment by nickboldt** [comment]
I assume we should also backport this to 7.9.x and CRW?

**Comment by tolusha** [comment]
@nickboldt 
There is no necessity . It is just an example in the csv file.

**Comment by nickboldt** [comment]
if this isn't code that's run then why did the olm test fail? :man_facepalming:

**Comment by tolusha** [comment]
```
[=============== [INFO] Starting minishift VM to test openshift olm files... ===============]
.ci/cico_olm_prcheck.sh: line 42: minishift: command not found
! "minikube" profile does not exist, trying anyways.
* Removed all traces of the "minikube" cluster.
.ci/cico_olm_prcheck.sh: line 17: minishift: command not found
Connection to 172.19.2.78 closed.
```
@flacatus Could you have a look pls

**Comment by flacatus** [comment]
> ```
> [=============== [INFO] Starting minishift VM to test openshift olm files... ===============]
> .ci/cico_olm_prcheck.sh: line 42: minishift: command not found
> ! "minikube" profile does not exist, trying anyways.
> * Removed all traces of the "minikube" cluster.
> .ci/cico_olm_prcheck.sh: line 17: minishift: command not found
> Connection to 172.19.2.78 closed.
> ```
> 
> @flacatus Could you have a look pls

Yes, right now.

**Pull request merged**
